### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by CJure** [lann/RFDuinoTest#3]
When I start the application I find my device by scan button, when I try to connect nothing happens. Only state of TextView Disconncted changes to Connecting... 

I also downloaded the apk. from: http://www.rfduino.com/product/rfduino-android-application/ and funny thing is that if I connect to RFduino there I also get data in my application. So it looks that is listening to data, but it won't start connection on it's own.

I am using Nesxus 5.

I had put  Log.v inside RFduinoService initialize(), but nothing happens.

**Comment by lann** [comment]
Sorry, I'm no longer maintaining this project. You might be able to find help at http://forum.rfduino.com/
