### ISSUE TITLE
Descriptor on UUID_CLIENT_CONFIGURATION

### ISSUE THREAD

**Issue by asherraz** [lann/RFDuinoTest#4]
Hey this isn't an issue, just a general question. 

In the RFduinoService file, how do you add the Descriptor to the UUID_CLIENT_CONFIGURATION characteristic so that the following line doesn't return Null?

BluetoothGattDescriptor receiveConfigDescriptor = receiveCharacteristic.getDescriptor(UUID_CLIENT_CONFIGURATION);

I see line 72 with: 
public final static UUID UUID_CLIENT_CONFIGURATION = BluetoothHelper.sixteenBitUuid(0x2902);

I'm working with another Bluetooth module: http://www.microchip.com/wwwproducts/Devices.aspx?product=RN4020

And I can't seem to find a way to set a Descriptor on a Private Characteristic.

Thanks for any help.

**Comment by lann** [comment]
This code is somewhat specific to RFduino, especially the hard-coded uuids. I don't have much general experience with BTLE so I'm afraid I can't help you here.
